### ISSUE TITLE
Error when running script

### ISSUE THREAD

**Issue by g-chataing** [kelvinxuande/glassdoor-scraper#3]
Hello, 

When running the script, (after cloning, without modifying config.json), I had the following error: 

```
[ERROR] Assumptions invalid
Traceback (most recent call last):
  File "<path>/glassdoor-scraper-master/src/main.py", line 68, in <module>
    maxJobs, maxPages = extract_maximums(base_url)
  File "<path>/glassdoor-scraper-master/src/packages/page.py", line 31, in extract_maximums
    return(int(maxJobs), int(maxPages))
ValueError: invalid literal for int() with base 10: ''
```

I believed that Glassdoor frontend was changed, thus the code on this project needs to be updated. 

Bests,
Gauthier

**Comment by patrickcnkm** [comment]
In line 17 of page.py, make the following change:
    tmp_match_2 = [item for item in page_soup.find_all("div") if "data-test" in item.attrs][-2]

This issue can be solved.

**Comment by kelvinxuande** [comment]
Hi @g-chataing , @patrickcnkm ; thanks for the comments! :) @patrickcnkm would you be able to submit a pull request for this? - Much appreciated!

Thanks and best regards,
Kelvin Tan
